# -*- coding: utf-8 -*-
"""A/B test marketing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qM1WIsq22gDbMqinLPEPzZ1i2X0IPogY
"""

import pandas as pd
import numpy as np
from scipy import stats
import math
from scipy.stats import ttest_ind

# read csv data
data = pd.read_csv('marketing_AB.csv')
data.head()

# Melihat ukuran data
data.shape

# Drop Unnamed: 0 karena merupakan index yang tidak dibutuhkan
data = data.drop('Unnamed: 0',axis = 1)
data

"""Pre Analysis"""

# Check data duplikat
data.duplicated(['user id']).sum()

# Check missing value
data.isna().sum()

# Lihat bentuk data
data.shape

# Lihat ringkasan data
data.info()

"""Penghitungan sample size"""

# calculate the conversion rate of control group
filt = (data['test group'].str.contains('psa')) & (data['converted'] == True)
num_conv_psa = len(data[filt])
num_psa = data['test group'].value_counts()['psa']
conv_rate_psa = num_conv_psa / num_psa
conv_rate_psa

# calculate standard deviation based on the control group conversion rate
std_dev = np.sqrt(conv_rate_psa * (1 - conv_rate_psa))
std_dev

# calculate sample size
alpha = 0.05  # significance level, industry standard value
power = 0.8  # industry standard value
delta = 0.01  # given value
z_alpha = stats.norm.ppf(1 - alpha / 2)
z_beta = stats.norm.ppf(power)
sample_size = math.ceil(2 * (std_dev ** 2) * ((z_beta + z_alpha) ** 2) / (delta ** 2))
sample_size

# Split users into Group A and Group B based on most ads day
most_ads_day = data['most ads day'].mode()[0]
group_a = data[data['most ads day'] == most_ads_day]
group_b = data[data['most ads day'] != most_ads_day]

# Randomly select samples from each group based on the calculated sample size
sample_a = group_a.sample(n=sample_size, replace=False)
sample_b = group_b.sample(n=sample_size, replace=False)

# Concatenate the samples
sample = pd.concat([sample_a, sample_b])

# Reset the index of the sample
sample.reset_index(drop=True, inplace=True)

# Print the sample
print(sample)

"""A/B Test Experiment

Eksperimen A/B Test Berdasarkan Hari Paling Banyak Iklan Dilihat: Data dibagi menjadi dua kelompok, yaitu kelompok A yang akan melihat iklan pada hari yang paling banyak iklan dilihat (most ads day) dan kelompok B yang akan melihat iklan pada hari yang lain. Kemudian dapat membandingkan konversi (converted) antara kedua kelompok untuk melihat apakah hari dengan frekuensi iklan yang tinggi berdampak pada peningkatan konversi.
"""

# Perform A/B test
t_statistic, p_value = ttest_ind(sample_a['converted'], sample_b['converted'], equal_var=False)

# Define significance level
alpha = 0.05

# Print the results
print(f"Conversion rate for Group A: {sample_a['converted'].mean()}")
print(f"Conversion rate for Group B: {sample_b['converted'].mean()}")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

# Perform hypothesis testing
if p_value < alpha:
    print("Reject the null hypothesis.")
    print("There is a significant difference in conversion rates between Group A and Group B.")
else:
    print("Fail to reject the null hypothesis.")
    print("There is no significant difference in conversion rates between Group A and Group B.")